[package]
name = "eerie"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Gyungmin Myung"]
description = "Rustic binding to the IREE Compiler/Runtime"
readme = "README.md"
repository = "https://github.com/gmmyung/eerie"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iree-sys = { path = "iree-sys" }
thiserror = "1.0.48"
tracing = "0.1.37"

[workspace]
members = [
    "iree-sys"
]

[dev-dependencies]
anyhow = "1.0.75"
rusty-fork = "0.3.0"
test-log = { version = "0.2.12", features = ["trace"], default-features = false }
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "fmt"] }

[features]
default = ["runtime", "compiler"]
runtime = ["iree-sys/runtime"]
compiler = ["iree-sys/compiler"]

[[example]]
name = "resnet"
test = false
bench = true

