[package]
name = "iree-sys"
version = "0.1.0"
edition = "2021"

[build-dependencies]
bindgen = "0.68.1"
cmake = "0.1.50"

[features]
default = ["compiler", "from-python", "runtime"]
from-python = ["compiler"]
from-source = ["compiler"]
compiler = []
runtime = []

